/**
 * `forge diagram validate --gate <G-Design|G-Deliver>` and `forge diagram generate --all --check`: the diagram checks
 * the shipped design and delivery gates name (`10` §10.3; `08` §8.11.7's `diagram:*` gate checks), added by
 * `PLAN-M13.md` P26 (Q228).
 *
 * **What is read.** The KB's diagrams: each is a sidecar (`<path>.mmd.yaml`, `08` §8.11.5) beside its source
 * (`<path>.mmd`, the file the sidecar describes; the engine's output check requires both). The rest is project state the
 * §8.11.7 checks need: the component inventory and every artifact id (for `depicts` references), the ADRs (structural
 * coverage), the DataModel documents (persistent state), `paths` and `project.level`/`diagrams.*` from the config. No
 * network, no renderer, no model. The parser is the pure-JS one `08` §8.11.8 names.
 *
 * **`--gate G-Design`** (`10` §10.3's own comment on the check: "syntax, required coverage, ADR diagram coverage, node
 * refs, captions"): every diagram parses (`diagram:syntax`), has its `depicts` resolved (`diagram:refs`), sound labels,
 * a caption and alt text (`requireCaptions`), and stays within the hard complexity limit; at L2 and above the context
 * and container views exist (`architecture/views/context.mmd`, `containers.mmd`, `08` §8.11.3) ; when a DataModel
 * exists (at any level) an ER diagram does; and every structural ADR (category architecture or data, or a blast radius naming more
 * than one component) contains a Mermaid block that parses or lists a registered diagram (`diagram:adr-coverage`). Drift is the
 * separate `diagram:drift` check (`generate --all --check`), not repeated here.
 *
 * **`--gate G-Deliver`** ("deployment topology and pipeline diagrams present and current"): at L2 and above,
 * `delivery/views/pipeline.mmd` and at least one `delivery/views/deployment-<env>.mmd` exist, and each is valid by the
 * checks above and not stale (`review_by` not in the past: `diagram:staleness`, a warning everywhere else in §8.11.7,
 * is an error here because the gate says "current").
 *
 * **`generate --all --check`** (`08` §8.11.6, "for every `generated: true` diagram, a check regenerates it and
 * compares"): regenerates each generated diagram from project state and compares it with its source. Only two of the
 * eight generators have a project-state reader: `components-to-c4` (the component inventory) and `specgraph-to-graph`
 * (the spec graph). A generated diagram from any other generator cannot be regenerated by a command that reads only
 * project state, so it is reported as unverifiable and counts as drifted (a check that cannot show a diagram is in sync
 * has not passed); `forge diagram diff <id> --input <json>` is the manual route, and the honest bypass is
 * `generated: false` or a Waiver. `diagrams.driftPolicy: warn` turns every finding into a warning (the spec's own
 * setting); `autofix` is checked like `fail`, because a gate check never writes.
 *
 * **Not checked here** (recorded in Q228): sequence diagrams per cross-boundary flow, component views (L3+), state
 * diagrams and the other rows of §8.11.3, whose triggers are prose facts no artifact records; `diagram:transclusion`
 * and `diagram:render`; `diagram:refs` for ER diagrams, whose nodes are entity names no registry holds.
 *
 * @see specs/08 §8.11.3, §8.11.6, §8.11.7
 * @see specs/10 §10.3
 * @see PLAN-M13.md P26
 */
import { SYSTEM_CLOCK, type Clock } from '@forge/core';
import { SpecGraph } from '@forge/core/graph';
import { readTextFile } from '@forge/core/fs';
import type { ProjectPaths } from '@forge/core/fs';
import { checkDrift } from '@forge/diagrams/drift';
import { GENERATOR_NAMES } from '@forge/diagrams/generate';
import { lintDiagram, type DiagramFinding } from '@forge/diagrams/lint';
import { parseDiagram } from '@forge/diagrams/parse';
import { parseKbTree, type KbParsedEntry } from '@forge/kb/schema';
import type { Diagram } from '@forge/schemas';

import type { GateCheckOutcome, GateViolation } from './gate-check-output.ts';
import { loadGraphDocs } from './spec.ts';
import {
  compare,
  errorMessage,
  oneLine,
  readSpecDocuments,
  walkFiles,
  type SpecDocuments,
} from './spec/spec-files.ts';

export type DiagramGate = 'G-Design' | 'G-Deliver';
export const DIAGRAM_GATES: readonly DiagramGate[] = ['G-Design', 'G-Deliver'];

export interface DiagramGateContext {
  readonly paths: ProjectPaths;
  readonly kbRoot: string;
  readonly specsRoot: string;
  /** `project.level` from the config (`L0`..`L4`). */
  readonly level: string;
  readonly diagrams: {
    readonly complexity: {
      readonly maxNodes: number;
      readonly maxEdges: number;
      readonly hardMaxNodes: number;
    };
    readonly requireCaptions: boolean;
    readonly driftPolicy: 'fail' | 'autofix' | 'warn';
  };
  readonly clock?: Clock;
}

/** More diagrams than this is a runaway tree; each parse loads the Mermaid parser. */
const MAX_DIAGRAMS = 500;
const MAX_SOURCE_CHARS = 1024 * 1024;

const CONTEXT_VIEW = 'architecture/views/context.mmd';
const CONTAINER_VIEW = 'architecture/views/containers.mmd';
const PIPELINE_VIEW = 'delivery/views/pipeline.mmd';
const DEPLOYMENT_VIEW = /^delivery\/views\/deployment-[^/]+\.mmd$/;
const DECIDED_STRUCTURE = new Set(['architecture', 'data']);
const NOT_DECIDED = new Set(['rejected', 'superseded', 'deprecated']);
const FENCE_OPEN = /^[ \t]*(`{3,}|~{3,})[ \t]*mermaid\b/i;
/** Blocks parsed per ADR and per run: each failed parse costs about a millisecond, and an ADR body is not trusted. */
const MAX_BLOCKS_PER_ADR = 20;
const MAX_BLOCKS_PER_RUN = 400;
/** ADR bodies are read up to here; the first fences matter, a hostile body must not cost more. */
const MAX_ADR_BODY_CHARS = 256 * 1024;

/** The Mermaid blocks of a Markdown body, in order (line by line: no backtracking scan). */
function mermaidBlocks(body: string): readonly string[] {
  const blocks: string[] = [];
  let open: { readonly fence: string; readonly lines: string[] } | undefined;
  for (const line of body.slice(0, MAX_ADR_BODY_CHARS).split(/\r\n|\r|\n/)) {
    if (open === undefined) {
      const match = FENCE_OPEN.exec(line);
      if (match?.[1] !== undefined) open = { fence: match[1], lines: [] };
    } else if (line.trim().startsWith(open.fence)) {
      blocks.push(open.lines.join('\n'));
      open = undefined;
    } else {
      open.lines.push(line);
    }
  }
  return blocks;
}

/** An ADR "contains a diagram" when one of its first Mermaid blocks parses: an empty or garbage fence shows nothing.
 * `budget` is shared across the run; running out is reported as such, never as a slow pass. */
async function containsDiagram(
  body: string,
  budget: { left: number },
): Promise<'yes' | 'no' | 'budget'> {
  const blocks = mermaidBlocks(body);
  for (const block of blocks.slice(0, MAX_BLOCKS_PER_ADR)) {
    if (budget.left <= 0) return 'budget';
    budget.left -= 1;
    try {
      await parseDiagram(block);
      return 'yes';
    } catch {
      // not a diagram: try the next block
    }
  }
  return blocks.length > MAX_BLOCKS_PER_ADR ? 'budget' : 'no';
}

function requiresCoverage(level: string): boolean {
  return level === 'L2' || level === 'L3' || level === 'L4';
}

interface LoadedDiagram {
  /** The sidecar's path relative to the KB root; the source is this without `.yaml`. */
  readonly sidecar: string;
  readonly source: string;
  readonly diagram: Diagram;
}

function diagramEntries(
  entries: readonly KbParsedEntry[],
): readonly { readonly path: string; readonly value: Diagram }[] {
  return entries.flatMap((entry) =>
    entry.kind === 'diagram' ? [{ path: entry.path, value: entry.value }] : [],
  );
}

function sourceOf(sidecar: string): string {
  return sidecar.endsWith('.yaml') ? sidecar.slice(0, -'.yaml'.length) : sidecar;
}

function violation(subject: string, message: string, remedy: string): GateViolation {
  return { subject, message, remedy };
}

function sorted(list: readonly GateViolation[]): GateViolation[] {
  return [...list].sort((a, b) => compare(a.subject, b.subject) || compare(a.message, b.message));
}

/** The KB's own vocabulary a diagram's `depicts` may name: components, every artifact id, every KB entry and register
 * id, and every id a KB entry says it `applies_to` (how a project registers a datastore or actor it draws). */
function knownIds(
  entries: readonly KbParsedEntry[],
  specs: SpecDocuments,
): { readonly ids: ReadonlySet<string>; readonly problems: readonly GateViolation[] } {
  const ids = new Set<string>();
  for (const entry of entries) {
    switch (entry.kind) {
      case 'adr':
      case 'diagram':
      case 'runbook':
        ids.add(entry.value.id);
        break;
      case 'kb-entry':
        ids.add(entry.value.id);
        for (const target of entry.value.applies_to) ids.add(target);
        break;
      case 'risks-file':
        for (const risk of entry.value.risks) ids.add(risk.id);
        break;
      case 'assumptions-file':
        for (const assumption of entry.value.assumptions) ids.add(assumption.id);
        break;
      case 'open-questions-file':
        for (const question of entry.value.open_questions) ids.add(question.id);
        break;
      case 'environments-file':
        for (const environment of entry.value.environments) ids.add(environment.id);
        break;
      case 'components-file':
        for (const component of entry.value.components) ids.add(component.id);
        break;
    }
  }
  for (const doc of specs.docs) {
    const id = (doc.frontMatter as Record<string, unknown>)['id'];
    if (typeof id === 'string') ids.add(id);
  }
  return { ids, problems: specs.unreadable };
}

async function loadDiagrams(
  ctx: DiagramGateContext,
  entries: readonly KbParsedEntry[],
): Promise<{
  readonly loaded: readonly LoadedDiagram[];
  readonly problems: readonly GateViolation[];
}> {
  const problems: GateViolation[] = [];
  const loaded: LoadedDiagram[] = [];
  const all = diagramEntries(entries);
  if (all.length > MAX_DIAGRAMS) {
    problems.push(
      violation(
        ctx.kbRoot,
        `More than ${String(MAX_DIAGRAMS)} diagrams under ${ctx.kbRoot}: they cannot be checked in full.`,
        'Split the knowledge base or remove diagrams that are no longer used, then run the check again.',
      ),
    );
  }
  for (const entry of all.slice(0, MAX_DIAGRAMS)) {
    const source = sourceOf(entry.path);
    try {
      const text = await readTextFile(ctx.paths.resolveWithin(`${ctx.kbRoot}/${source}`));
      if (text.length > MAX_SOURCE_CHARS) {
        problems.push(
          violation(
            entry.value.id,
            `${entry.value.id}: ${source} is over the ${String(MAX_SOURCE_CHARS)} character limit, so it cannot be checked.`,
            `Split ${source} into layered views (08 section 8.11.7 complexity).`,
          ),
        );
        continue;
      }
      loaded.push({ sidecar: entry.path, source: text, diagram: entry.value });
    } catch (cause) {
      problems.push(
        violation(
          entry.value.id,
          `${entry.value.id}: its source ${ctx.kbRoot}/${source} cannot be read (${oneLine(errorMessage(cause))}).`,
          `Write the diagram source at ${ctx.kbRoot}/${source}, beside its sidecar ${entry.path}.`,
        ),
      );
    }
  }
  return { loaded, problems };
}

/** Sidecars that failed their schema and `.mmd` files with no sidecar at all: a diagram nobody can validate. */
async function unregistered(
  ctx: DiagramGateContext,
  entries: readonly KbParsedEntry[],
  errors: readonly { readonly path: string; readonly message: string }[],
): Promise<readonly GateViolation[]> {
  const problems: GateViolation[] = [];
  for (const error of errors) {
    if (error.path === ctx.kbRoot || error.path.endsWith('.mmd.yaml')) {
      problems.push(
        violation(
          error.path,
          `${error.path} could not be read (${oneLine(error.message)}), so the diagram it describes cannot be checked.`,
          `Repair the sidecar ${error.path} (08 section 8.11.5: id, kind, notation, source, generated, depicts, explains, caption, alt_text, owner).`,
        ),
      );
    }
  }
  const registered = new Set(diagramEntries(entries).map((entry) => sourceOf(entry.path)));
  const broken = new Set(errors.map((error) => sourceOf(error.path)));
  const files = await walkFiles(ctx, ctx.kbRoot);
  if (files.capped) {
    problems.push(
      violation(
        ctx.kbRoot,
        `More than 5000 files under ${ctx.kbRoot}: diagram sources with no sidecar cannot be found in full.`,
        `Move what is not knowledge base content out of ${ctx.kbRoot}, then run the check again.`,
      ),
    );
  }
  for (const file of files.files) {
    const relative = file.slice(ctx.kbRoot.length + 1);
    if (!relative.endsWith('.mmd') || registered.has(relative) || broken.has(relative)) continue;
    problems.push(
      violation(
        relative,
        `${relative} has no sidecar ${relative}.yaml, so it is not a registered Diagram and cannot be checked.`,
        `Add ${relative}.yaml describing the diagram (08 section 8.11.5), or delete the file.`,
      ),
    );
  }
  return problems;
}

// --- diagram validate --gate ----------------------------------------------------------------------------

export async function diagramValidateGate(
  ctx: DiagramGateContext,
  gate: DiagramGate,
): Promise<GateCheckOutcome> {
  const tree = await parseKbTree(ctx.paths, ctx.kbRoot);
  const violations: GateViolation[] = [...(await unregistered(ctx, tree.entries, tree.errors))];
  if (gate === 'G-Design') {
    // An ADR that fails its schema is missing from the structural-coverage pass below: a decision nobody can read
    // has not been shown to carry a diagram.
    for (const error of tree.errors.filter((candidate) =>
      candidate.path.startsWith('decisions/'),
    )) {
      violations.push(
        violation(
          error.path,
          `${error.path} could not be read (${oneLine(error.message)}), so its diagram coverage cannot be checked.`,
          `Repair the front matter of ${error.path} (the ADR schema), then run the check again.`,
        ),
      );
    }
  }
  const { loaded, problems } = await loadDiagrams(ctx, tree.entries);
  violations.push(...problems);
  // Read once: two readers of one corrupt file would count it twice.
  const specs = await readSpecDocuments(
    ctx,
    ctx.specsRoot,
    'what a diagram depicts and whether persistent state exists',
    'interfaces',
  );
  const known = knownIds(tree.entries, specs);
  violations.push(...known.problems);
  const warnings: GateViolation[] = [];
  const now = new Date((ctx.clock ?? SYSTEM_CLOCK).now());

  // The diagrams the gate is about: all of them at G-Design, the deployment and pipeline views at G-Deliver.
  const inScope = loaded.filter((entry) => {
    if (gate === 'G-Design') return true;
    const source = sourceOf(entry.sidecar);
    return source === PIPELINE_VIEW || DEPLOYMENT_VIEW.test(source);
  });

  let parsedKinds = new Set<string>();
  for (const entry of inScope) {
    const { diagram } = entry;
    let parsed: Awaited<ReturnType<typeof parseDiagram>>;
    try {
      parsed = await parseDiagram(entry.source);
    } catch (cause) {
      violations.push(
        violation(
          diagram.id,
          `${diagram.id} (diagram:syntax): ${oneLine(errorMessage(cause))}`,
          `Fix the syntax of ${ctx.kbRoot}/${sourceOf(entry.sidecar)} so it parses as ${diagram.notation}.`,
        ),
      );
      continue;
    }
    parsedKinds = new Set([...parsedKinds, parsed.kind]);
    const skipRefs = parsed.kind === 'erDiagram';
    const findings: readonly DiagramFinding[] = lintDiagram(diagram, parsed, {
      ...(skipRefs ? {} : { knownIds: known.ids }),
      complexity: ctx.diagrams.complexity,
      requireCaptions: ctx.diagrams.requireCaptions,
      now,
    });
    for (const finding of findings) {
      const staleAtDelivery = gate === 'G-Deliver' && finding.checkId === 'diagram:staleness';
      const item = violation(
        diagram.id,
        `${diagram.id} (${finding.checkId}): ${finding.message}`,
        remedyFor(finding),
      );
      if (finding.severity === 'error' || staleAtDelivery) violations.push(item);
      else warnings.push(item);
    }
  }

  const sources = new Set(loaded.map((entry) => sourceOf(entry.sidecar)));
  const level = requiresCoverage(ctx.level);
  let required = 0;
  const need = (present: boolean, subject: string, what: string, where: string): void => {
    required += 1;
    if (present) return;
    violations.push(
      violation(
        subject,
        `Required diagram missing (diagram:required, level ${ctx.level}): ${what}.`,
        `Draw it at ${ctx.kbRoot}/${where} with its .mmd.yaml sidecar (08 section 8.11.3).`,
      ),
    );
  };
  if (level && gate === 'G-Design') {
    need(sources.has(CONTEXT_VIEW), CONTEXT_VIEW, 'the system context view', CONTEXT_VIEW);
    need(sources.has(CONTAINER_VIEW), CONTAINER_VIEW, 'the container view', CONTAINER_VIEW);
  }
  if (gate === 'G-Design') {
    // `08` §8.11.3: an ER diagram is required "whenever persistent state exists", at every level.
    const persistent = specs.docs.some((doc) => {
      const fm = doc.frontMatter as Record<string, unknown>;
      return (
        fm['type'] === 'DataModel' &&
        !(typeof fm['status'] === 'string' && NOT_DECIDED.has(fm['status']))
      );
    });
    if (persistent) {
      need(
        parsedKinds.has('erDiagram'),
        'data/views',
        'an entity-relationship diagram (a DataModel exists, so persistent state does)',
        'data/views/er-<context>.mmd',
      );
    }
  }
  if (level && gate === 'G-Deliver') {
    need(sources.has(PIPELINE_VIEW), PIPELINE_VIEW, 'the CI/CD pipeline diagram', PIPELINE_VIEW);
    need(
      [...sources].some((source) => DEPLOYMENT_VIEW.test(source)),
      'delivery/views',
      'a deployment topology diagram',
      'delivery/views/deployment-<env>.mmd',
    );
  }

  // diagram:adr-coverage: a structural ADR contains a diagram or references one that exists.
  let structural = 0;
  const budget = { left: MAX_BLOCKS_PER_RUN };
  if (gate === 'G-Design') {
    const registeredIds = new Set(diagramEntries(tree.entries).map((entry) => entry.value.id));
    for (const entry of tree.entries) {
      if (entry.kind !== 'adr' || NOT_DECIDED.has(entry.value.status)) continue;
      const adr = entry.value;
      if (!DECIDED_STRUCTURE.has(adr.category) && adr.blast_radius.length < 2) continue;
      structural += 1;
      const dangling = adr.diagrams.filter((id) => !registeredIds.has(id));
      for (const id of dangling) {
        violations.push(
          violation(
            adr.id,
            `${adr.id} (diagram:adr-coverage) lists diagram ${oneLine(id, 60)}, which is not a registered Diagram.`,
            `Register ${oneLine(id, 60)} (a .mmd.yaml sidecar) or remove it from ${adr.id}'s diagrams.`,
          ),
        );
      }
      const contained =
        adr.diagrams.length === 0 ? await containsDiagram(entry.body, budget) : 'yes';
      if (contained === 'budget') {
        violations.push(
          violation(
            adr.id,
            `${adr.id} (diagram:adr-coverage): too many Mermaid blocks to check (more than ${String(MAX_BLOCKS_PER_ADR)} in one ADR, or ${String(MAX_BLOCKS_PER_RUN)} in the run) and none of the first ones parsed.`,
            `Put one diagram in ${adr.id} or list a registered diagram in its diagrams.`,
          ),
        );
      } else if (contained === 'no') {
        violations.push(
          violation(
            adr.id,
            `${adr.id} (diagram:adr-coverage): a structural ADR (category ${adr.category}, blast radius ${String(adr.blast_radius.length)}) contains no Mermaid block that parses and lists no diagram.`,
            `Add a ## Diagram section with a Mermaid block to ${adr.id}, or list a registered diagram in its diagrams.`,
          ),
        );
      }
    }
  }

  const sortedViolations = sorted(violations);
  return {
    fields: {
      check: 'diagram-validate',
      gate,
      diagrams: inScope.length,
      required,
      structural_adrs: structural,
      warnings_count: warnings.length,
    },
    violations: sortedViolations,
    warnings: sorted(warnings),
  };
}

function remedyFor(finding: DiagramFinding): string {
  switch (finding.checkId) {
    case 'diagram:refs':
      return "Make every depicts entry a real component, artifact id or KB entry id (or list it under a KB entry's applies_to), or remove it.";
    case 'diagram:label-quality':
      return 'Replace the empty, single-letter or placeholder label with a real name.';
    case 'diagram:caption':
      return 'Write a real caption and alt_text in the diagram sidecar.';
    case 'diagram:complexity':
      return 'Split the diagram into layered views under the node budget.';
    case 'diagram:staleness':
      return 'Review the diagram against the system and move review_by forward.';
    case 'diagram:orphan-nodes':
      return 'Connect the node or remove it (usually a typo).';
    case 'diagram:drift':
    case 'diagram:transclusion':
      return 'Regenerate the diagram from its source.';
  }
}

// --- diagram generate --all --check ----------------------------------------------------------------------

type Verdict =
  | { readonly kind: 'in-sync' }
  | { readonly kind: 'drifted' }
  | { readonly kind: 'unverifiable'; readonly why: string };

async function inputFor(
  ctx: DiagramGateContext,
  generator: string,
  entries: readonly KbParsedEntry[],
): Promise<{ readonly input: unknown } | { readonly why: string }> {
  if (generator === 'components-to-c4') {
    const components = entries.flatMap((entry) =>
      entry.kind === 'components-file' ? entry.value.components : [],
    );
    if (components.length === 0) {
      return { why: 'the component inventory (architecture/components.md) has no components' };
    }
    return {
      input: {
        components: components.map((component) => ({
          id: component.id,
          label: component.label,
          dependsOn: component.dependsOn,
        })),
      },
    };
  }
  if (generator === 'specgraph-to-graph') {
    const docs = await loadGraphDocs({
      paths: ctx.paths,
      specsRoot: ctx.specsRoot,
      kbRoot: ctx.kbRoot,
    });
    return { input: { graph: SpecGraph.build(docs) } };
  }
  return {
    why: `no command that reads only project state can regenerate a ${generator} diagram (only components-to-c4 and specgraph-to-graph have a project-state reader)`,
  };
}

export async function diagramDriftCheck(ctx: DiagramGateContext): Promise<GateCheckOutcome> {
  const tree = await parseKbTree(ctx.paths, ctx.kbRoot);
  const violations: GateViolation[] = [];
  const warnings: GateViolation[] = [];
  // A diagram whose sidecar cannot be read might be a generated one: report it rather than skip it.
  const unread = tree.errors.filter(
    (error) => error.path === ctx.kbRoot || error.path.endsWith('.mmd.yaml'),
  );
  for (const error of unread) {
    violations.push(
      violation(
        error.path,
        `${error.path} could not be read (${oneLine(error.message)}), so it cannot be shown to be in sync.`,
        `Repair the sidecar ${error.path}, then run the check again.`,
      ),
    );
  }
  const { loaded, problems } = await loadDiagrams(ctx, tree.entries);
  violations.push(...problems);

  let checked = 0;
  let inSync = 0;
  let mismatched = 0;
  let unverifiable = 0;
  const findings: GateViolation[] = [];
  for (const entry of loaded) {
    const { diagram } = entry;
    if (!diagram.generated) continue;
    checked += 1;
    const generator = (diagram.generator ?? '').replace(/^forge:/, '');
    let verdict: Verdict;
    if (!(GENERATOR_NAMES as readonly string[]).includes(generator)) {
      verdict = {
        kind: 'unverifiable',
        why: `its generator ${oneLine(diagram.generator ?? '(none)', 60)} is not one of ${GENERATOR_NAMES.join(', ')}`,
      };
    } else {
      try {
        const input = await inputFor(ctx, generator, tree.entries);
        if ('why' in input) {
          verdict = { kind: 'unverifiable', why: input.why };
        } else {
          verdict = checkDrift({ ...diagram, generator }, entry.source, input.input).hasDrift
            ? { kind: 'drifted' }
            : { kind: 'in-sync' };
        }
      } catch (cause) {
        verdict = {
          kind: 'unverifiable',
          why: `it could not be regenerated (${oneLine(errorMessage(cause))})`,
        };
      }
    }
    if (verdict.kind === 'in-sync') {
      inSync += 1;
    } else if (verdict.kind === 'drifted') {
      mismatched += 1;
      findings.push(
        violation(
          diagram.id,
          `${diagram.id} has drifted: ${generator} regenerates it differently from ${ctx.kbRoot}/${sourceOf(entry.sidecar)}.`,
          `Regenerate ${diagram.id} from its source (the component inventory or spec graph changed), or fix the source if the diagram is right.`,
        ),
      );
    } else {
      unverifiable += 1;
      findings.push(
        violation(
          diagram.id,
          `${diagram.id} cannot be shown in sync: ${verdict.why}.`,
          `Mark ${diagram.id} generated: false if it is hand-drawn, or check it with forge diagram diff ${diagram.id} --input <json> and record a Waiver.`,
        ),
      );
    }
  }
  const warnOnly = ctx.diagrams.driftPolicy === 'warn';
  (warnOnly ? warnings : violations).push(...findings);

  const sortedViolations = sorted(violations);
  return {
    fields: {
      check: 'diagram-drift',
      checked,
      in_sync: inSync,
      mismatched,
      unverifiable,
      // The one field the gate reads: every problem that stops a generated diagram being shown in sync (drifted,
      // unverifiable, or unreadable), except the drift findings themselves when the project's own
      // `diagrams.driftPolicy` says drift only warns (08 section 8.11.6).
      drifted: sortedViolations.length,
      drift_policy: ctx.diagrams.driftPolicy,
    },
    violations: sortedViolations,
    warnings: sorted(warnings),
  };
}
