/**
 * `taskSchema` — `specs/09` §9.3's Task (`TASK-###`).
 *
 * `09` §9.3 describes Task only in prose ("optional decomposition inside a story... generated by the
 * workflow, not usually hand-authored") and gives no field list or example, unlike Vision, Capability,
 * NFR, Epic and Story. This schema is the base front matter narrowed to `type: 'Task'`, with no
 * invented business fields. See `SPEC-QUESTIONS.md` Q20.
 *
 * @see specs/09 §9.3
 * @see SPEC-QUESTIONS.md Q20
 */
import { z } from 'zod';

import { baseFrontMatterShape, checkIdMatchesRegisteredType } from '../registry/front-matter.ts';

export const taskSchema = baseFrontMatterShape
  .extend({ type: z.literal('Task') })
  .strict()
  .superRefine(checkIdMatchesRegisteredType);

export type Task = z.infer<typeof taskSchema>;
